import { TarotCard } from '../types';

export const TAROT_DECK: TarotCard[] = [
  {
    id: 0,
    romanNumeral: '0',
    name: 'The Fool',
    vietnameseName: 'Kẻ Khờ (Khởi Đầu Mới)',
    element: 'Khí',
    planetOrSign: 'Sao Thiên Vương',
    icon: '🎒',
    themeColor: 'from-amber-400/20 via-yellow-500/10 to-transparent',
    keywords: ['Khởi đầu mới', 'Ngây thơ', 'Tự do', 'Tiềm năng vô hạn', 'Phiêu lưu'],
    uprightKeywords: ['Dấn thân', 'Cơ hội mới', 'Lạc quan', 'Phá vỡ giới hạn'],
    reversedKeywords: ['Bất cẩn', 'Thiếu chuẩn bị', 'Liều lĩnh vô ích'],
    archetype: 'Người lữ hành tâm linh bước vào chuyến hành trình vĩ đại',
    coreMessage: 'Hãy dũng cảm bước bước chân đầu tiên với tâm thế cởi mở, vũ trụ luôn bảo bọc những kẻ dám mơ lớn.',
    advice: 'Đừng để nỗi sợ thất bại kìm hãm bạn; ngày hôm nay là thời điểm lý tưởng để bắt đầu một dự định ấp ủ.'
  },
  {
    id: 1,
    romanNumeral: 'I',
    name: 'The Magician',
    vietnameseName: 'Ảo Thuật Gia (Năng Lực Hiện Thực Hóa)',
    element: 'Khí',
    planetOrSign: 'Sao Thủy',
    icon: '🪄',
    themeColor: 'from-yellow-400/20 via-amber-500/10 to-transparent',
    keywords: ['Hiện thực hóa', 'Trí tuệ', 'Tài năng', 'Tập trung', 'Quyền năng'],
    uprightKeywords: ['Làm chủ vận mệnh', 'Biến ý tưởng thành hiện thực', 'Kỹ năng xuất sắc'],
    reversedKeywords: ['Phân tán năng lượng', 'Thiếu tự tin', 'Thao túng'],
    archetype: 'Người kết nối trời và đất, bậc thầy điều khiển các nguyên tố',
    coreMessage: 'Bạn nắm trong tay đầy đủ mọi công cụ và nguồn lực để biến ước mơ thành hiện thực.',
    advice: 'Hãy tập trung 100% ý chí và hành động cụ thể; điều kỳ diệu sẽ xuất hiện ngay trong ngày hôm nay.'
  },
  {
    id: 2,
    romanNumeral: 'II',
    name: 'The High Priestess',
    vietnameseName: 'Nữ Tu Tế (Trực Giác Thấu Thị)',
    element: 'Nước',
    planetOrSign: 'Mặt Trăng',
    icon: '🌙',
    themeColor: 'from-blue-400/20 via-indigo-500/10 to-transparent',
    keywords: ['Trực giác', 'Bí ẩn', 'Tĩnh lặng', 'Tiềm thức', 'Tri thức ngầm'],
    uprightKeywords: ['Lắng nghe tiếng nói bên trong', 'Bí mật được hé lộ', 'Tâm hồn sâu sắc'],
    reversedKeywords: ['Phớt lờ linh cảm', 'Rối bời cảm xúc', 'Bí bách nội tâm'],
    archetype: 'Người gác cổng bức màn bí ẩn giữa thế giới hữu hình và vô hình',
    coreMessage: 'Hãy lắng nghe trực giác thầm kín của bạn, câu trả lời không nằm ở bên ngoài mà nằm ngay trong tâm thức.',
    advice: 'Dành 10-15 phút tĩnh tâm, tránh vội vã đưa ra quyết định dựa trên lời nói bên ngoài.'
  },
  {
    id: 3,
    romanNumeral: 'III',
    name: 'The Empress',
    vietnameseName: 'Nữ Hoàng (Trù Phú & Nuôi Dưỡng)',
    element: 'Đất',
    planetOrSign: 'Sao Kim',
    icon: '👑',
    themeColor: 'from-emerald-400/20 via-green-500/10 to-transparent',
    keywords: ['Trù phú', 'Sinh sôi', 'Tình mẫu tử', 'Sáng tạo', 'Tự nhiên'],
    uprightKeywords: ['Thịnh vượng gõ cửa', 'Chăm sóc bản thân', 'Ý tưởng thăng hoa'],
    reversedKeywords: ['Bỏ bê bản thân', 'Kiểm soát quá mức', 'Cạn kiệt năng lượng'],
    archetype: 'Đất Mẹ trù phú, hiện thân của tình yêu thương và sự sinh sôi nảy nở',
    coreMessage: 'Hạt giống bạn đã gieo trồng đang bắt đầu đơm hoa kết trái; hãy tận hưởng sự sung túc và bình an.',
    advice: 'Chăm sóc cơ thể, hòa mình vào thiên nhiên và đối xử thật dịu dàng với chính bản thân.'
  },
  {
    id: 4,
    romanNumeral: 'IV',
    name: 'The Emperor',
    vietnameseName: 'Hoàng Đế (Kỷ Luật & Uy Quyền)',
    element: 'Lửa',
    planetOrSign: 'Bạch Dương',
    icon: '🏛️',
    themeColor: 'from-rose-500/20 via-red-600/10 to-transparent',
    keywords: ['Lãnh đạo', 'Cấu trúc', 'Kỷ luật', 'Vững chãi', 'Trật tự'],
    uprightKeywords: ['Kiểm soát tình thế', 'Quyết đoán', 'Thiết lập ranh giới vững chắc'],
    reversedKeywords: ['Độc đoán', 'Cứng nhắc', 'Thiếu linh hoạt'],
    archetype: 'Người kiến tạo trật tự, trụ cột vững chắc của xã hội',
    coreMessage: 'Thành công hôm nay đến từ sự kỷ luật, quy tắc rõ ràng và tinh thần trách nhiệm không lay chuyển.',
    advice: 'Hãy lập kế hoạch chi tiết, làm chủ cảm xúc và dứt khoát giải quyết việc quan trọng nhất.'
  },
  {
    id: 5,
    romanNumeral: 'V',
    name: 'The Hierophant',
    vietnameseName: 'Đại Tư Tế (Minh Triết & Cội Nguồn)',
    element: 'Đất',
    planetOrSign: 'Kim Ngưu',
    icon: '📜',
    themeColor: 'from-amber-600/20 via-orange-600/10 to-transparent',
    keywords: ['Minh triết', 'Truyền thống', 'Học hỏi', 'Đạo đức', 'Cố vấn'],
    uprightKeywords: ['Tìm kiếm lời khuyên từ tiền bối', 'Gắn kết cộng đồng', 'Học tập sâu'],
    reversedKeywords: ['Giáo điều', 'Bó buộc', 'Cần tư duy phản biện'],
    archetype: 'Bậc thầy dẫn đường tâm linh, cầu nối giữa chân lý và đời sống',
    coreMessage: 'Hãy tìm kiếm sự hướng dẫn từ những bậc tiền bối uyên bác hoặc các giá trị cốt lõi trường tồn.',
    advice: 'Mở lòng học hỏi điều mới và tôn trọng những nguyên tắc đạo đức đã chứng minh qua thời gian.'
  },
  {
    id: 6,
    romanNumeral: 'VI',
    name: 'The Lovers',
    vietnameseName: 'Đôi Tình Nhân (Lựa Chọn & Gắn Kết)',
    element: 'Khí',
    planetOrSign: 'Song Tử',
    icon: '💞',
    themeColor: 'from-pink-500/20 via-rose-500/10 to-transparent',
    keywords: ['Tình yêu', 'Hòa hợp', 'Lựa chọn của trái tim', 'Đồng điệu', 'Hợp tác'],
    uprightKeywords: ['Sự kết nối thiêng liêng', 'Quyết định đúng đắn', 'Hòa hợp tâm hồn'],
    reversedKeywords: ['Bất đồng quan điểm', 'Do dự lựa chọn', 'Mất cân bằng'],
    archetype: 'Sự hợp nhất giữa hai thái cực, lựa chọn dựa trên sự chân thành tối thượng',
    coreMessage: 'Một sự hòa hợp sâu sắc đang diễn ra; hãy đưa ra quyết định bằng tiếng gọi thuần khiết của trái tim.',
    advice: 'Hãy trân trọng các mối quan hệ quan trọng và thành thật với những gì mình khao khát.'
  },
  {
    id: 7,
    romanNumeral: 'VII',
    name: 'The Chariot',
    vietnameseName: 'Cỗ Xe Chiến Thắng (Ý Chí Đột Phá)',
    element: 'Nước',
    planetOrSign: 'Cự Giải',
    icon: '⚔️',
    themeColor: 'from-sky-500/20 via-blue-600/10 to-transparent',
    keywords: ['Chiến thắng', 'Ý chí sắt đá', 'Tiến lên', 'Vượt chướng ngại', 'Kiểm soát'],
    uprightKeywords: ['Bứt phá ngoạn mục', 'Tập trung cao độ', 'Chiến thắng thử thách'],
    reversedKeywords: ['Mất phương hướng', 'Nóng vội', 'Va chạm không đáng có'],
    archetype: 'Chiến binh quả cảm chế ngự hai lực lượng đối lập để lao nhanh về đích',
    coreMessage: 'Không có chướng ngại nào cản được bước chân người có ý chí sắt đá và mục tiêu rõ ràng.',
    advice: 'Giữ chặt tay lái cuộc đời mình; dũng cảm tiến lên phía trước mà không quay đầu nhìn lại.'
  },
  {
    id: 8,
    romanNumeral: 'VIII',
    name: 'Strength',
    vietnameseName: 'Sức Mạnh (Nội Lực & Ôn Nhu)',
    element: 'Lửa',
    planetOrSign: 'Sư Tử',
    icon: '🦁',
    themeColor: 'from-amber-500/20 via-yellow-600/10 to-transparent',
    keywords: ['Nội lực', 'Lòng trắc ẩn', 'Ôn nhu thắng cương', 'Kiên nhẫn', 'Dũng cảm'],
    uprightKeywords: ['Chế ngự nỗi sợ', 'Tâm từ bi', 'Sức chịu đựng phi thường'],
    reversedKeywords: ['Tự ti', 'Cảm xúc bộc phát', 'Dễ buông xuôi'],
    archetype: 'Người phụ nữ dùng tình thương thuần khiết thuần hóa chúa tể sơn lâm',
    coreMessage: 'Sức mạnh lớn nhất không phải bạo lực mà là sự kiên nhẫn, lòng trắc ẩn và sự điềm tĩnh sâu sắc.',
    advice: 'Đối diện mọi tranh cãi bằng nụ cười và sự thấu cảm; bạn sẽ làm chủ mọi tình huống.'
  },
  {
    id: 9,
    romanNumeral: 'IX',
    name: 'The Hermit',
    vietnameseName: 'Ẩn Sĩ (Soi Rọi Nội Tâm)',
    element: 'Đất',
    planetOrSign: 'Xử Nữ',
    icon: '🕯️',
    themeColor: 'from-slate-400/20 via-zinc-500/10 to-transparent',
    keywords: ['Tĩnh lặng', 'Tự chiêm nghiệm', 'Ngọn đèn dẫn lối', 'Tìm kiếm chân lý', 'Độc lập'],
    uprightKeywords: ['Hiểu rõ bản thân', 'Tìm ra giải pháp trong tĩnh lặng', 'Trí tuệ tích lũy'],
    reversedKeywords: ['Cô lập thái quá', 'Xa rời thực tế', 'Cảm giác cô đơn'],
    archetype: 'Kẻ độc hành cầm ngọn đèn trí tuệ soi sáng con đường tuyết trắng',
    coreMessage: 'Rút lui khỏi những ồn ào thế sự để nhìn sâu vào tâm mình; ngọn đèn chân lý đang sáng tỏ.',
    advice: 'Dành không gian riêng cho chính bạn hôm nay để lắng nghe tiếng nói sâu thẳm nhất.'
  },
  {
    id: 10,
    romanNumeral: 'X',
    name: 'Wheel of Fortune',
    vietnameseName: 'Bánh Xe Số Phận (Vận May & Bước Ngoặt)',
    element: 'Lửa',
    planetOrSign: 'Sao Mộc',
    icon: '☸️',
    themeColor: 'from-purple-500/20 via-brand-gold/10 to-transparent',
    keywords: ['Vận may', 'Bước ngoặt', 'Nhân quả', 'Thời cơ vàng', 'Chuyển hóa'],
    uprightKeywords: ['Cơ hội ngàn vàng', 'Vận đỏ gõ cửa', 'Thay đổi tích cực bất ngờ'],
    reversedKeywords: ['Sự chậm trễ tạm thời', 'Cần chấp nhận quy luật', 'Đừng cưỡng cầu'],
    archetype: 'Vòng xoay luân hồi mang lại những chuyển biến kỳ diệu của vũ trụ',
    coreMessage: 'Bánh xe số phận đang xoay theo chiều hướng thuận lợi nhất; hãy sẵn sàng đón nhận phúc lành.',
    advice: 'Nắm bắt ngay khi cơ hội xuất hiện; thái độ tích cực sẽ thu hút những điều may mắn tột bực.'
  },
  {
    id: 11,
    romanNumeral: 'XI',
    name: 'Justice',
    vietnameseName: 'Công Lý (Cân Bằng & Chân Lý)',
    element: 'Khí',
    planetOrSign: 'Thiên Bình',
    icon: '⚖️',
    themeColor: 'from-teal-400/20 via-emerald-500/10 to-transparent',
    keywords: ['Công bằng', 'Chân lý', 'Cân bằng', 'Quyết định đúng', 'Minh bạch'],
    uprightKeywords: ['Kết quả xứng đáng', 'Minh bạch rõ ràng', 'Lấy lại sự cân bằng'],
    reversedKeywords: ['Thiếu công bằng', 'Tránh né trách nhiệm', 'Phán xét vội vàng'],
    archetype: 'Nữ thần công lý tay cầm kiếm sắc tay cầm cán cân phân minh',
    coreMessage: 'Mọi hành động đều có nhân quả; sự trung thực và minh bạch sẽ mang lại kết quả trọn vẹn nhất.',
    advice: 'Hãy đánh giá mọi sự việc một cách khách quan, không thiên vị và đứng về phía lẽ phải.'
  },
  {
    id: 12,
    romanNumeral: 'XII',
    name: 'The Hanged Man',
    vietnameseName: 'Kẻ Treo Ngược (Góc Nhìn Khác Biệt)',
    element: 'Nước',
    planetOrSign: 'Sao Hải Vương',
    icon: '🧘‍♂️',
    themeColor: 'from-cyan-400/20 via-blue-500/10 to-transparent',
    keywords: ['Đổi mới góc nhìn', 'Buông bỏ', 'Khai sáng', 'Kiên nhẫn', 'Sự hi sinh ý nghĩa'],
    uprightKeywords: ['Nhìn thấy cơ hội trong bế tắc', 'Buông bỏ áp lực', 'Giác ngộ mới'],
    reversedKeywords: ['Cố chấp vô ích', 'Trì hoãn', 'Cảm giác mắc kẹt'],
    archetype: 'Người treo ngược thân mình để nhìn thế giới với một góc nhìn hoàn toàn mới',
    coreMessage: 'Khi sự việc không theo ý bạn, hãy đổi góc nhìn; sự buông bỏ đôi khi là chìa khóa mở ra cánh cửa mới.',
    advice: 'Đừng vội thúc ép mọi thứ; hãy thả lỏng và quan sát vấn đề từ một lăng kính trái ngược.'
  },
  {
    id: 13,
    romanNumeral: 'XIII',
    name: 'Death',
    vietnameseName: 'Tái Sinh (Khép Lại Để Tái Khởi)',
    element: 'Nước',
    planetOrSign: 'Bọ Cạp',
    icon: '🦋',
    themeColor: 'from-violet-500/20 via-purple-600/10 to-transparent',
    keywords: ['Tái sinh', 'Chuyển hóa', 'Khép lại chu kỳ cũ', 'Lột xác', 'Giải phóng'],
    uprightKeywords: ['Cắt tỉa cành khô', 'Khởi sắc sau giai đoạn cũ', 'Lột xác ngoạn mục'],
    reversedKeywords: ['Sợ thay đổi', 'Bám víu quá khứ', 'Trì hoãn lột xác'],
    archetype: 'Quy luật tái sinh bất diệt, lá khô rụng xuống để chồi non nảy lộc',
    coreMessage: 'Khép lại những gì không còn phục vụ sự tiến hóa của bạn để chào đón một chương đời rạng rỡ hơn.',
    advice: 'Dứt khoát từ bỏ những thói quen cũ hoặc mối quan hệ độc hại để tái tạo nguồn sinh khí mới.'
  },
  {
    id: 14,
    romanNumeral: 'XIV',
    name: 'Temperance',
    vietnameseName: 'Tiết Chế (Hài Hòa & Dung Hòa)',
    element: 'Lửa',
    planetOrSign: 'Nhân Mã',
    icon: '🏺',
    themeColor: 'from-sky-400/20 via-emerald-500/10 to-transparent',
    keywords: ['Hài hòa', 'Chữa lành', 'Tiết chế', 'Dung hòa', 'Kiên nhẫn'],
    uprightKeywords: ['Bình ổn cảm xúc', 'Tìm thấy điểm cân bằng', 'Chữa lành nội tâm'],
    reversedKeywords: ['Mất cân đối', 'Thái quá', 'Nóng vội thiếu kiên nhẫn'],
    archetype: 'Thiên thần rót dòng nước thần qua lại giữa hai chiếc bình vàng bạc',
    coreMessage: 'Bí quyết của hạnh phúc và thành công hôm nay nằm ở sự dung hòa và chừng mực vừa phải.',
    advice: 'Tránh mọi hành vi cực đoan; hãy kết hợp mềm dẻo giữa làm việc và nghỉ ngơi.'
  },
  {
    id: 15,
    romanNumeral: 'XV',
    name: 'The Devil',
    vietnameseName: 'Ác Quỷ (Giải Thoát Cám Dỗ)',
    element: 'Đất',
    planetOrSign: 'Ma Kết',
    icon: '🔥',
    themeColor: 'from-red-600/20 via-rose-700/10 to-transparent',
    keywords: ['Nhận diện cám dỗ', 'Bóng tối nội tâm', 'Xiềng xích vô hình', 'Tự do ý chí'],
    uprightKeywords: ['Nhìn rõ sự ràng buộc', 'Thức tỉnh trước ảo tưởng', 'Lấy lại quyền kiểm soát'],
    reversedKeywords: ['Vượt qua thói quen xấu', 'Giải phóng bản thân', 'Thoát khỏi thao túng'],
    archetype: 'Bóng tối nội tâm thử thách ý chí và sự tự do của linh hồn',
    coreMessage: 'Chiếc xiềng xích đang trói buộc bạn thực chất rất lỏng lẻo; bạn hoàn toàn có thể tự tháo bỏ nó.',
    advice: 'Thành thật với những thói quen tiêu cực và dũng cảm nói "Không" với những điều độc hại.'
  },
  {
    id: 16,
    romanNumeral: 'XVI',
    name: 'The Tower',
    vietnameseName: 'Tòa Tháp Đổ (Thức Tỉnh Đột Phá)',
    element: 'Lửa',
    planetOrSign: 'Sao Hỏa',
    icon: '⚡',
    themeColor: 'from-orange-500/20 via-red-600/10 to-transparent',
    keywords: ['Thức tỉnh đột ngột', 'Phá vỡ ảo tưởng', 'Tái thiết nền móng', 'Chân lý xuất hiện'],
    uprightKeywords: ['Giải thoát bất ngờ', 'Nhìn rõ thực tại', 'Xây dựng lại từ gốc rễ'],
    reversedKeywords: ['Tránh né sự thật', 'Cố chấp níu giữ', 'Sợ sụp đổ'],
    archetype: 'Tia sét vũ trụ đánh tan bức tường ảo tưởng để lộ ra bầu trời chân lý',
    coreMessage: 'Sự sụp đổ của một ảo tưởng chính là sự giải thoát để bạn xây dựng lại trên nền tảng vững chắc hơn.',
    advice: 'Đừng hoảng sợ trước những biến động bất ngờ; đó là cơ hội vàng để tái sinh mạnh mẽ hơn.'
  },
  {
    id: 17,
    romanNumeral: 'XVII',
    name: 'The Star',
    vietnameseName: 'Ngôi Sao (Hy Vọng & Phép Màu)',
    element: 'Khí',
    planetOrSign: 'Bảo Bình',
    icon: '⭐',
    themeColor: 'from-indigo-400/20 via-sky-500/10 to-transparent',
    keywords: ['Hy vọng', 'Chữa lành', 'Ánh sáng dẫn đường', 'Niềm tin', 'Cảm hứng'],
    uprightKeywords: ['Phép màu xuất hiện', 'Bình yên trở lại', 'Tương lai tươi sáng'],
    reversedKeywords: ['Mất niềm tin tạm thời', 'Hoài nghi', 'Cần nạp lại năng lượng'],
    archetype: 'Ngôi sao rạng rỡ tỏa ánh sáng dịu lành xuống dòng nước tâm hồn',
    coreMessage: 'Sau cơn mưa trời lại sáng; vũ trụ đang rót tràn nguồn năng lượng chữa lành và cảm hứng vào bạn.',
    advice: 'Hãy giữ vững niềm tin và ước nguyện; vũ trụ đang âm thầm sắp đặt những điều tốt đẹp nhất.'
  },
  {
    id: 18,
    romanNumeral: 'XVIII',
    name: 'The Moon',
    vietnameseName: 'Mặt Trăng (Trực Giác & Mộng Mị)',
    element: 'Nước',
    planetOrSign: 'Song Ngư',
    icon: '🌕',
    themeColor: 'from-violet-400/20 via-blue-600/10 to-transparent',
    keywords: ['Trực giác', 'Giấc mơ', 'Vượt qua ảo ảnh', 'Tiềm thức', 'Nhạy cảm'],
    uprightKeywords: ['Linh cảm cực nhạy', 'Thấy rõ bản chất qua sương mù', 'Khám phá chiều sâu'],
    reversedKeywords: ['Hoang mang lo âu vô cớ', 'Hiểu lầm', 'Cần sự rõ ràng'],
    archetype: 'Ánh trăng huyền ảo soi rọi đáy sâu đại dương tiềm thức',
    coreMessage: 'Đừng để những nỗi lo âu mơ hồ làm bạn chùn bước; hãy dùng trực giác để xuyên qua màn sương.',
    advice: 'Chú ý đến các giấc mơ và linh cảm; kiểm chứng lại thông tin trước khi đưa ra kết luận quan trọng.'
  },
  {
    id: 19,
    romanNumeral: 'XIX',
    name: 'The Sun',
    vietnameseName: 'Mặt Trời (Hào Quang & Niềm Vui)',
    element: 'Lửa',
    planetOrSign: 'Mặt Trời',
    icon: '☀️',
    themeColor: 'from-amber-400/25 via-yellow-500/15 to-transparent',
    keywords: ['Hào quang', 'Thành công rực rỡ', 'Niềm vui', 'Sức sống dồi dào', 'Rõ ràng'],
    uprightKeywords: ['May mắn tột đỉnh', 'Tràn đầy năng lượng', 'Tỏa sáng rực rỡ'],
    reversedKeywords: ['Niềm vui bị che khuất tạm thời', 'Quá tự tin', 'Cần giữ khiêm tốn'],
    archetype: 'Vầng thái dương chiếu rọi ánh sáng ấm áp mang lại sự sống cho muôn loài',
    coreMessage: 'Ánh hào quang rực rỡ đang bao bọc lấy bạn; niềm vui, thành công và sự viên mãn đang ở ngay trước mắt.',
    advice: 'Tự tin tỏa sáng, mỉm cười và lan tỏa nguồn năng lượng tích cực đến mọi người xung quanh.'
  },
  {
    id: 20,
    romanNumeral: 'XX',
    name: 'Judgement',
    vietnameseName: 'Phán Xét (Thức Tỉnh Sứ Mệnh)',
    element: 'Lửa',
    planetOrSign: 'Sao Diêm Vương',
    icon: '📯',
    themeColor: 'from-rose-400/20 via-purple-500/10 to-transparent',
    keywords: ['Thức tỉnh', 'Tiếng gọi sứ mệnh', 'Đánh giá lại', 'Tha thứ', 'Tái sinh tinh thần'],
    uprightKeywords: ['Lắng nghe tiếng gọi thiêng liêng', 'Chuyển biến tâm thức', 'Bước sang trang mới'],
    reversedKeywords: ['Tự phán xét khắt khe', 'Do dự trước ngã rẽ', 'Chần chừ thức tỉnh'],
    archetype: 'Tiếng kèn thiên thần đánh thức linh hồn bước lên tầng nhận thức cao hơn',
    coreMessage: 'Tiếng gọi của sứ mệnh đang vang lên; hãy tha thứ cho quá khứ và tự tin bước vào phiên bản tốt nhất của bạn.',
    advice: 'Lắng nghe trực giác về một quyết định quan trọng mà bạn đã trì hoãn bấy lâu nay.'
  },
  {
    id: 21,
    romanNumeral: 'XXI',
    name: 'The World',
    vietnameseName: 'Thế Giới (Viên Mãn & Toàn Vẹn)',
    element: 'Đất',
    planetOrSign: 'Sao Thổ',
    icon: '🌍',
    themeColor: 'from-emerald-400/25 via-teal-500/15 to-transparent',
    keywords: ['Viên mãn', 'Hoàn thành trọn vẹn', 'Thành tựu đỉnh cao', 'Hòa hợp vũ trụ'],
    uprightKeywords: ['Về đích thành công', 'Mở ra chân trời toàn cầu', 'Sự hài lòng tuyệt đối'],
    reversedKeywords: ['Thiếu một bước cuối', 'Trì hoãn hoàn tất', 'Cần kiên trì đến cùng'],
    archetype: 'Vũ điệu chiến thắng trong vòng nguyệt quế của sự toàn vẹn vũ trụ',
    coreMessage: 'Bạn đã đi qua một hành trình dài và đang chạm tới sự viên mãn, hoàn tất trọn vẹn một chương vĩ đại.',
    advice: 'Tự hào về những gì bạn đã đạt được và sẵn sàng cho những nấc thang vươn tầm cao hơn.'
  }
];

export function getRandomTarotCard(): { card: TarotCard; isReversed: boolean } {
  const randomIndex = Math.floor(Math.random() * TAROT_DECK.length);
  // Optional reversed chance (25% chance for subtle depth)
  const isReversed = Math.random() < 0.25;
  return {
    card: TAROT_DECK[randomIndex],
    isReversed
  };
}

export function getShuffledDeck(): TarotCard[] {
  const deck = [...TAROT_DECK];
  for (let i = deck.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [deck[i], deck[j]] = [deck[j], deck[i]];
  }
  return deck;
}
